# Generated by Django 5.1.1 on 2024-09-13 16:43

import django.core.validators
import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('sur_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('pincode', models.CharField(validators=[myapp.models.validate_numeric, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(6)])),
                ('phone', models.IntegerField(validators=[myapp.models.validate_phone])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
