# Generated by Django 5.1.1 on 2024-09-14 03:44

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='career_objective',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_location', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('SL', 'Select'), ('HSD', 'High school Diploma'), ('GED', 'GED'), ('AOA', 'Associate of Arts'), ('AOS', 'Associate of science'), ('AAS', 'Associate of Applied science'), ('BA', 'Bachelor of Arts'), ('BE', 'Bachelor of Engineering'), ('BTECH', 'Bachelor of Technology'), ('BBA', 'BBA'), ('MAS', 'Master of Science'), ('MAA', 'Master of Arts'), ('JD', 'J.D'), ('MD', 'M.D.'), ('PHD', 'PH.D.'), ('ND', 'No Degree')], default='SL', max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('CGPA', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField()),
                ('linked_in', models.CharField()),
                ('github', models.CharField()),
                ('leet_code', models.CharField()),
                ('other_link', models.CharField(null=True)),
                ('projects', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name=[('python', 'Python'), ('django', 'Django'), ('flask', 'Flask'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('java', 'Java'), ('spring', 'Spring'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('objective_c', 'Objective-C'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('rails', 'Ruby on Rails'), ('php', 'PHP'), ('laravel', 'Laravel'), ('symfony', 'Symfony'), ('go', 'Go (Golang)'), ('rust', 'Rust'), ('perl', 'Perl'), ('r', 'R'), ('matlab', 'MATLAB'), ('sql', 'SQL'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('firebase', 'Firebase'), ('graphql', 'GraphQL'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('linux', 'Linux'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud Platform'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('travisci', 'Travis CI'), ('selenium', 'Selenium'), ('cypress', 'Cypress'), ('pytest', 'Pytest'), ('unittest', 'UnitTest'), ('junit', 'JUnit'), ('cucumber', 'Cucumber'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow'), ('scikit_learn', 'Scikit-Learn'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('opencv', 'OpenCV')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='working_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('your_role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'working_info',
            },
        ),
    ]
