# Generated by Django 5.1.1 on 2024-09-14 08:41

import django.core.validators
import multiselectfield.db.fields
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userinfo_career_objective_education_others_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('flask', 'Flask'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('java', 'Java'), ('spring', 'Spring'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('objective_c', 'Objective-C'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('rails', 'Ruby on Rails'), ('php', 'PHP'), ('laravel', 'Laravel'), ('symfony', 'Symfony'), ('go', 'Go (Golang)'), ('rust', 'Rust'), ('perl', 'Perl'), ('r', 'R'), ('matlab', 'MATLAB'), ('sql', 'SQL'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('firebase', 'Firebase'), ('graphql', 'GraphQL'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('linux', 'Linux'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud Platform'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('travisci', 'Travis CI'), ('selenium', 'Selenium'), ('cypress', 'Cypress'), ('pytest', 'Pytest'), ('unittest', 'UnitTest'), ('junit', 'JUnit'), ('cucumber', 'Cucumber'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow'), ('scikit_learn', 'Scikit-Learn'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('opencv', 'OpenCV')], max_length=447),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(validators=[myapp.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pincode',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
