# Generated by Django 5.1.1 on 2024-09-14 09:20

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_education_field_of_study_alter_skills_skills_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pincode',
            field=models.CharField(validators=[myapp.models.validate_numeric, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
