# Generated by Django 5.1.1 on 2024-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_job_title_working_info_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_info',
            name='role_description',
            field=models.TextField(blank=True),
        ),
    ]
