# Generated by Django 5.1.1 on 2024-09-14 12:01

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_working_info_role_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('objective_c', 'Objective-C'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('php', 'PHP'), ('go', 'Go (Golang)'), ('rust', 'Rust'), ('perl', 'Perl'), ('r', 'R'), ('sql', 'SQL')], max_length=108)),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('rails', 'Ruby on Rails'), ('laravel', 'Laravel'), ('symfony', 'Symfony'), ('graphql', 'GraphQL'), ('firebase', 'Firebase'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow'), ('scikit_learn', 'Scikit-Learn'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('opencv', 'OpenCV')], max_length=161)),
                ('core', multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('git', 'Git'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('linux', 'Linux'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud Platform'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('travisci', 'Travis CI'), ('selenium', 'Selenium'), ('cypress', 'Cypress'), ('pytest', 'Pytest'), ('unittest', 'UnitTest'), ('junit', 'JUnit'), ('vscode', 'VS Code'), ('intellij', 'IntelliJ IDEA'), ('eclipse', 'Eclipse IDE'), ('github_actions', 'GitHub Actions'), ('gitlab_ci', 'GitLab CI'), ('nginx', 'NGINX'), ('apache', 'Apache HTTP Server')], default='None', max_length=207)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
