# Generated by Django 5.1.1 on 2024-09-14 12:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_skill_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='core',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('git', 'Git'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('linux', 'Linux'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'Google Cloud Platform'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('travisci', 'Travis CI'), ('selenium', 'Selenium'), ('cypress', 'Cypress'), ('pytest', 'Pytest'), ('unittest', 'UnitTest'), ('junit', 'JUnit'), ('vscode', 'VS Code'), ('intellij', 'IntelliJ IDEA'), ('eclipse', 'Eclipse IDE'), ('github_actions', 'GitHub Actions'), ('gitlab_ci', 'GitLab CI'), ('nginx', 'NGINX'), ('apache', 'Apache HTTP Server')], max_length=202),
        ),
    ]
