# Generated by Django 5.1.1 on 2024-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_skill_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='CGPA',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
