# Generated by Django 5.1.1 on 2024-09-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_working_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_info', to='myapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='others',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='myapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_info', to='myapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='working_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_info', to='myapp.userinfo'),
        ),
    ]
