# Generated by Django 5.1.1 on 2024-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_working_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='portfolio',
            field=models.CharField(blank=True),
        ),
    ]
