# Generated by Django 5.1.1 on 2024-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('SL', 'Select'), ('HSD', 'High school Diploma'), ('GED', 'GED'), ('AOA', 'Associate of Arts'), ('AOS', 'Associate of science'), ('AAS', 'Associate of Applied science'), ('BA', 'Bachelor of Arts'), ('B.E', 'Bachelor of Engineering'), ('BTECH', 'Bachelor of Technology'), ('BBA', 'BBA'), ('MS', 'Master of Science'), ('MAA', 'Master of Arts'), ('JD', 'J.D'), ('MD', 'M.D.'), ('PH.D', 'PH.D.'), ('ND', 'No Degree')], default='SL', max_length=5),
        ),
    ]
